### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by FoksVHox** [mbezhanov/faker-provider-collection#11]
How would you prefer us to test new providers? I'm working on a new provider and I'd like to know how I should test them. Or shouldn't I test it at all?

**Comment by mbezhanov** [comment]
Hi @FoksVHox, all providers have to be unit tested. You can find tests that you can use as an example in https://github.com/mbezhanov/faker-provider-collection/tree/master/tests/Faker/Provider

It's sufficient to test that the provider you created returns values of the desired type and format.

Let me know if you require any further assistance with this.

**Comment by FoksVHox** [comment]
> Hi @FoksVHox, all providers have to be unit tested. You can find tests that you can use as an example in https://github.com/mbezhanov/faker-provider-collection/tree/master/tests/Faker/Provider
> 
> It's sufficient to test that the provider you created returns values of the desired type and format.
> 
> Let me know if you require any further assistance with this.

Is it just done with PHPUnit, or? I'm not totally sure how I'll be able to test it.

If you're able to help me, you can contact me on Discord, Foks#2279.

**Comment by FoksVHox** [comment]
@mbezhanov

**Comment by mbezhanov** [comment]
Hi @FoksVHox, unfortunately I will have to go ahead and close this issue, as I am unable to provide mentoring/support over Discord at this point in time, due to my limited availability. There are a lot of tests in https://github.com/mbezhanov/faker-provider-collection/tree/master/tests/Faker/Provider that you can use as example for writing tests for your own providers. I hope these help at least a little to get your started.
