### ISSUE TITLE
Guide to use it with Laravel

### ISSUE THREAD

**Issue by prionkor** [mbezhanov/faker-provider-collection#3]
Hello,

First of all, thank you very much for this wonderful library. Could you add a guide to use it with laravel?

**Comment by prionkor** [comment]
i was able to do it

**Comment by mbezhanov** [comment]
Hi, I am happy to hear that you are making good use of this library, and that you were able to solve the issue yourself.

However, I just wanted to point out that I have described how to use the library with Laravel before in this issue: https://github.com/mbezhanov/faker-provider-collection/issues/2

And because your request duplicated the request from https://github.com/mbezhanov/faker-provider-collection/issues/2, I decided to develop a separate package, which exposes a Laravel service provider that automatically registers the library with your Laravel application.

The new package is located at: https://github.com/mbezhanov/laravel-faker-provider-collection

Using it is as simple as doing:

`composer require --dev mbezhanov/laravel-faker-provider-collection`.

Then you should be able to use the library in your Laravel app, without any further configuration.
