### ISSUE TITLE
Commerce->department resets unique values

### ISSUE THREAD

**Issue by oskar-addiator** [mbezhanov/faker-provider-collection#9]
https://github.com/mbezhanov/faker-provider-collection/blob/1d9df5b44297d93327b3eadd8babd3458945cac2/src/Faker/Provider/Commerce.php#L36
true should be false or omitted.

**Comment by oskar-addiator** [comment]
I also belive productName has problems with uniqueness but I will have yet to verify.

**Comment by mbezhanov** [comment]
Hi Oskar, we reset the unique values here, so that each new department may contain a combination of unique categories, even if a previous department also had some of these categories.

Without `$this->generator->unique()`, calling `$this->faker->department` may return nonsense like: `Books, Books & Books`.

With `$this->generator->unique()`  it will always return a combination of different categories e.g. "Books, Movies & Music". However, a subsequent call to `$this->faker->department` will not be able to use any of these three categories, unless we use `unique(true)` to reset the generator. Without `unique(true)` the provider will quickly run out of categories and throw an error.

`$this->faker->department` is not meant to enforce uniqueness of the departments. In other words, it is expected and normal to have two subsequent calls return the same department, e.g. "Books, Movies & Music"

I hope this clarifies how the department generation was meant to work. Let me know if I can assist you further with this and what issue you are facing because of this.

Thank you!

**Comment by oskar-addiator** [comment]
Interesting. Maybe one could implement a private copy of https://github.com/fzaninotto/Faker/blob/master/src/Faker/UniqueGenerator.php and use that internally and leave original functionally from Faker alone, that though wouldn't be a one line fix. Closing as it works as intended.
